var Quotes = [
["say hi to a stranger"],
["take more photos"],
["send a 2 page handwritten letter to a friend"],
["watch an episode of oprah"],
["upload a video on youtube"],
["speak up"],
["knit a scarf"],
["encourage a co-worker"],
["plant a tree (or two or three)"],
["take risks"],
["eat a whole tomato like an apple"],
["stay away from gas station slushies"],
["be more understanding"],
["think before I speak"],
["start a piggie bank"],
["learn to say hello in 5 languages"],
["be remarkable"],
["re-read a book from high school"],
["grow basil"],
["change the world"],
["carpool"],
["be patient"],
["listen"],
["be productive"],
["cook beef bourguignon"],
["read a dr. seuss book"],
["organize my desktop"],
["send birthday cards"],
["drink more water"],
["use double sided tape"],
["bake cookies from scratch"],
["friend a person with the same name as me on facebook"],
["hopscotch"],
["wear mittens"],
["start a pencil collection"],
["strike up a conversation with a stranger"],
["create something that betters the lives of others"],
["make someone\u0027s day"],
["take a break"],
["bring a reusable bag to the grocery store"],
["create! create! create!"],
["start a sticker collection"],
["make a paper airplane"],
["watch a movie in 3d"],
["go cloud watching (and find an animal or two)"],
["reconnect with an old friend"],
["get to know the neighbors"],
["have a garage sale"],
["write a love letter"],
["send a thank you card"],
["high five the person sitting next to me"],
["throw a penny in a fountain"],
["make a paper collage"],
["try harder"],
["be carefree"],
["avoid drama"],
["be a leader"],
["start or actually update my blog"],
["throw a party"],
["dance"],
["watch a documentary"],
["get jiggy wit it"],
["calm down"],
["frost cupcakes"],
["roast marshmallows over a fire"],
["travel"],
["become an expert on something"],
["make fresh pasta"],
["play the kazoo"],
["declutter"],
["write a story"],
["follow through"],
["be happy and healthy"],
["wake up earlier"],
["lighten up"],
["be serious"],
["appreciate the simple things"],
["love"],
["floss"],
["talk more, tweet less"],
["be positive"],
["be honest"],
["stay in touch"],
["inspire"],
["donate my time"],
["find mr. or ms. right"],
["run a marathon"],
["do what i love"],
["spend my money wisely"],
["smile"],
["laugh a lot"],
["carry a purse"],
["give up a bad habit"],
["wear sunglasses"],
["skip"],
["eat a mango"],
["leave a large tip"],
["make friends"],
["spread joy"],
["be present in each moment"],
["visit an art museum"],
["be a rockstar"],
["go camping"],
["appreciate nature"],
["make something new everyday"],
["smell the roses"],
["not make any resolutions"],
["learn to tie a tie"],
["try a new cafe"],
["use my phone to call instead of text"],
["touch my toes"],
["give a hug every day"],
["call mom and dad more often"],
["stop. collaborate. (and listen.)"],
["spend more time with the kids"],
["keep my family safe"],
["build a tree-house"],
["broaden my horizon"],
["be more tolerant"],
["go back to school"],
["sing out of tune"],
["eat well"],
["ride my bike"],
["spread kindness"],
["give"],
["give more compliments"],
["eat more fruit"],
["apply for my dream job"],
["take public transportation"],
["find live music"],
["throw a dinner party"],
["share the remote control"],
["jog"],
["let go"],
["drink more tea"],
["learn to commit"],
["learn to cope"],
["go to yoga"],
["start a business"],
["take more chances"],
["solve the rubik\u0027s cube"],
["live life to the fullest"],
["realize none of us are strangers"],
["tell her that I love her"],
["tell him that I love him"],
["enjoy the outdoors"],
["be spiritual"],
["draw everyday"],
["have fun"],
["start acting my age"],
["never give up"],
["find the time"],
["spend less time web browsing and more time doing"],
["be me"],
["meditate"],
["not dwell on the past"],
["move around"],
["look up at the sky"],
["take a deep breath"],
["spend more time with myself"],
["try my hand at astrophotography and photograph the stars!"],
["be brave"],
["compose a song"],
["do it"],
["be true to myself and others"],
["forgive him"],
["forgive her"],
["get a piercing"],
["be thankful"],
["show gratitude"],
["paint more"],
["be a better person"],
["turn off the tv"],
["be spontaneous"],
["win the lottery"],
["volunteer"],
["travel to tahiti"],
["sing in the shower"],
["care deeply"],
["get married"],
["make. more. money."],
["follow my own advice"],
["make a short film"],
["believe"],
["accept"],
["update my avatar"],
["perform random acts of kindness"],
["learn italian"],
["listen to my heart"],
["fall in love"],
["play"],
["throw a costume party"],
["dress up"],
["imagine"],
["be courageous"],
["stand tall"],
["see the good in people"],
["participate"],
["trust my instincts"],
["be available"],
["join a choir"],
["jump rope"],
["take accordion lessons"],
["tap my feet"],
["snap my fingers"],
["reuse"],
["reduce"],
["back up my computer files regularly"],
["make a wish"],
["make a quilt"],
["enjoy every minute"],
["go sailing"],
["fly to the moon"],
["focus"],
["think about it"],
["drink hot cocoa"],
["look for the silver lining"],
["pay it forward"],
["make my bed"],
["make a root beer float"],
["vacuum"],
["take a nap"],
["watch the sunrise"],
["watch the sunset"],
["be curious"],
["move on"],
["hold the door open for others"],
["moisturize"],
["flip pancakes"],
["take the stairs, not the escalator"],
["be on time"],
["improve"],
["get some sleep"],
["whistle"],
["work smarter"],
["slow down"],
["be fearless"],
["roll_over"],
["roll_out"],
["click less"],
["click more"],
["Exercise more"],
["Eat better"],
["Cut down on alcohol"],
["Stop smoking"],
["Spend less time on Facebook / Twitter"],
["Learn a new language"],
["Learn a musical instrument"],
["Spend less money"],
["Secure my dream job"],
["Average eight hours of sleep a night"],
["Improve my qualifications"],
["Spend more time with my kids"],
["Get a toned body like Beyonce"],
["Have cosmetic surgery"],
["Get a pet"],
["Ride my bike more"],
["Watch more news & documentaries"],
["Find a better partner"],
["Improve cooking skills"],
["Do more for charity"],
["Get a promotion at work"],
["Stop watching trashy reality TV"],
["Become more intimate"],
["See more of my friends"],
["Sponsor a child in Africa"],
["Eat less chocolate"],
["Drink less coffee"],
["Improve personal hygiene"],
["Drink more water"],
["More live music / entertainment"],
["Learn to bake a cake like Mary Berry"],
["More outdoor activities"],
["Take up a new sport"],
["Learn to knit"],
["Swear less"],
["Introduce a date night every other week with my partner"],
["Have a baby"],
["Take up a new sport"],
["Go to church more often"],
["Take the stairs"],
["Read more books"],
["Try to not get a parking fine/speeding ticket"],
["Pass driving test"],
["Eat fewer sweets"],
["Get married"],
["Break a world record"],
["Travel more"],
["Learn how to use technology properly (iPad, social media etc)"],
["Eat less red meat"],
["Spend less time at work"],
    ["Take up yoga."],
    ["Assign my kids regular chores, and make them follow through!"],
    ["Read for pleasure."],
    ["Walk a little slower and take in my surroundings."],
    ["Smile to at least one person every day."],
    ["Opt for the stairs a few times every week."],
    ["Shut off Netflix by 11PM."],
    ["Take up a new hobby."],
    ["Cook dinner more often."],
    ["Stop pressing snooze."], 
    ["Do one new thing every single week. It doesn’t have to be major."],
      ["Get out of my comfort zone and explore more."],
      ["Make the iPad the exception, not the habit, for nighttime entertainment."],
      ["Make a meal for any friend or neighbor when they’re sick or stuck at home."],
      ["Give more away—even if it’s something I want for myself."],
      ["Keep teaching my kids to have gratitude, and lead by example."],
      ["Practice an instrument more (or take up a new one)."],
      ["Stop using my phone as a crutch. People-watch, instead."],
      ["Be more of a team player."],
      ["Live more minimalistically."],
      ["Try my best to stay in the moment and enjoy that sweet (but potentially stressful) hour between arriving home from work and putting the baby to sleep."],
      ["Step up my morning game. Wake up early enough to have a leisurely breakfast and enjoy a cup of coffee."],
      ["Post more unfiltered and realistic images on your social feeds."],
      ["Say 'no' sometimes."],
      ["Finally donate unworn clothing to people who could use it."],
      ["Learn how to cook more of my favorite foods—no more take-out!"],
      ["Become a smart grocery shopper by utilizing lists and pantry inventory before I go."],
      ["Run a few miles every day."],
      ["Plan to visit extended family regularly."],
      ["Take fewer cars and cabs."],
      ["Spend one-on-one quality time with my friends every single week."],
      ["Talk to people on the phone more often."],
      ["Stop tying my child's shoes."],
      ["Go to the movies alone, or go to a restaurant alone, just to prove I can handle the me time."], 
  ["Plan at least one weekend day-trip every month."],
        ["Have 'date night' at least once a week."],
        ["Go on a blind date."],
        ["Get those piles of photos into scrapbooks."],
        ["Save money and make coffee at home."],
        ["Start using SPF every single day. Even in the winter."],
        ["Be less argumentative."],
        ["Strive to stand up for myself more often."],
        ["Tackle three DIY projects I’ve pinned in the last three months."],
        ["Meditate for five minutes every day."],
        ["Opt for tea instead of coffee."],
        ["Stop drinking soda."],
        ["Make an effort to respond to emails quickly so they don’t fall through the cracks."],
        ["Learn how to make basic, easy things I normally buy, because homemade tastes better—and it’s better for me."],
        ["Stop beating myself up over mistakes. Learn from them, and move on."],
        ["Resolve to work ahead and stop waiting until the last second."],
      ];
      var Q = Quotes.length;
      var Tweet = document.getElementById("tweet-button");
      var previousQuote = -1;

      function randQuote() {
        var currentQuote = Math.round(Math.random() * (Q - 1));
        while (currentQuote == previousQuote) {
          currentQuote = Math.round(Math.random() * (Q - 1));
        }
        previousQuote = currentQuote;
        document.getElementById("quote").innerHTML = Quotes[currentQuote][0];
                var twitterURL =  "https://twitter.com/intent/tweet?text=" + "I resolve to " + document.getElementById("quote").innerHTML + " @roceteer_inc"

        twitterURL = twitterURL.replace(/;/g, '%3B');
        Tweet.setAttribute("href", twitterURL);
      }
      window.onload = randQuote();